### ISSUE TITLE
It does not generate cash

### ISSUE THREAD

**Issue by Peppe-73** [Kamorzy/Portable-Crates#1]
Hi, I downloaded your Mod, I insert the materials required to create the crates, but they are not generated, I'm using Mc 1.20.4, could you solve the problem? Thank you

**Comment by Kamorzy** [comment]
I tested it on a fresh 1.20.4 instance and didn't have an issue. Make sure the iron ingots are placed in the corners of the crafting grid, not the middle slots. What wood planks are you using?

**Comment by Peppe-73** [comment]
Here is a screenshot, as you can see it generates nothing

![craft](https://github.com/Kamorzy/Portable-Crates/assets/50875260/be4ae34c-43d2-4745-9db9-2fd5dc57430a)

**Comment by Peppe-73** [comment]
If you like and want to try something I can wait for your trial version to download now
​

**Comment by Kamorzy** [comment]
Since I can't tell with the resource pack, make sure those are minecraft:iron_ingot and minecraft:acacia_planks in a minecraft:crafting_table. Does the crate appear in your recipe book? Also, could you post your latest.log?

**Comment by Peppe-73** [comment]
Yesterday I saw the boxes in the recipe book, today I didn't,
[latest.log](https://github.com/Kamorzy/Portable-Crates/files/14212862/latest.log)

![1](https://github.com/Kamorzy/Portable-Crates/assets/50875260/fa9565be-e531-4158-a847-9a2d95eb966f)
![2](https://github.com/Kamorzy/Portable-Crates/assets/50875260/137743a9-dd85-498b-aeff-151662805f6a)
![3](https://github.com/Kamorzy/Portable-Crates/assets/50875260/ea51aa19-1008-41a4-b04d-d4f9ae0e6dbc)

**Comment by Kamorzy** [comment]
Those planks look different than the orange ones from the first picture. I assumed they were acacia. What were the planks you used to try to make it?

**Comment by Peppe-73** [comment]
I tried all the planks, including those you specified, in your guide you don't specify a particular board but only boards, but I tried them all out of scruple.

Excuse my English but I use google

**Comment by Kamorzy** [comment]
Yeah, its recipe only uses the vanilla planks tag, so all planks should work as long as mod authors add theirs to it like they should. I wanted to see the mods you have installed + any errors that might have thrown in your log, but it doesn't include any system startup information. Since it works on a fresh instance, its likely a conflict with a mod or something else specific to your setup.

I'm not sure why yours reset after startup, but could you post the log when it still has the startup info of the mods in it?

**Comment by Peppe-73** [comment]
![MODS](https://github.com/Kamorzy/Portable-Crates/assets/50875260/0724af7d-0c90-4c49-b871-089752191d11)

**Comment by Kamorzy** [comment]
Okay, thats a short list. I'll install those mods and test it.

**Comment by Kamorzy** [comment]
It worked for me with those mods. However, there was some major issue with Iris 1.6.15, so they took it down. I tested with 1.6.14 instead. Then tested again without Iris at all + all the other mods with the exact versions you have. It still worked. Although its unlikely the 1.6.15 Iris bugs would touch anything with recipes.

Even if you had the recipe revoked somehow, it would still work and give it to you once you craft it once. Does the server owner have the same updated version installed server side?

**Comment by Peppe-73** [comment]
I'm the owner of the server, it doesn't work for me, I don't know what to tell you

**Comment by Peppe-73** [comment]
If you are the original Mc try to enter my server and see if mc.portalemc.it works

**Comment by Kamorzy** [comment]
Resolved, requires server side installation + more clear explanation for installations on servers in Modrinth

**Comment by Peppe-73** [comment]
Thanks for your availability, as I don't speak English I didn't see the description, the Google translations are a bit superficial, thanks bye
